# Generated by Django 4.1.7 on 2023-03-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Siteweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='User',
        ),
    ]
