# Generated by Django 4.1.7 on 2023-03-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Siteweb', '0003_rename_user_userinfo'),
    ]

    operations = [
    ]
